<?php
/**
 * THK Analytics - free/libre analytics platform
 *
 * @copyright Copyright (C) 2015 Thought is free.
 * @link http://thk.kanzae.net/analytics/
 * @license http://www.gnu.org/licenses/gpl-2.0.html GPL v2 or later
 * @author LunaNuko
 *
 * This program has been developed on the basis of the Research Artisan Lite.
 */
class PrefCityList {
	public static $prefs = array(
		'01' => '北海道',
		'02' => '青森県',
		'03' => '岩手県',
		'04' => '宮城県',
		'05' => '秋田県',
		'06' => '山形県',
		'07' => '福島県',
		'08' => '茨城県',
		'09' => '栃木県',
		'10' => '群馬県',
		'11' => '埼玉県',
		'12' => '千葉県',
		'13' => '東京都',
		'14' => '神奈川県',
		'15' => '新潟県',
		'16' => '富山県',
		'17' => '石川県',
		'18' => '福井県',
		'19' => '山梨県',
		'20' => '長野県',
		'21' => '岐阜県',
		'22' => '静岡県',
		'23' => '愛知県',
		'24' => '三重県',
		'25' => '滋賀県',
		'26' => '京都府',
		'27' => '大阪府',
		'28' => '兵庫県',
		'29' => '奈良県',
		'30' => '和歌山県',
		'31' => '鳥取県',
		'32' => '島根県',
		'33' => '岡山県',
		'34' => '広島県',
		'35' => '山口県',
		'36' => '徳島県',
		'37' => '香川県',
		'38' => '愛媛県',
		'39' => '高知県',
		'40' => '福岡県',
		'41' => '佐賀県',
		'42' => '長崎県',
		'43' => '熊本県',
		'44' => '大分県',
		'45' => '宮崎県',
		'46' => '鹿児島県',
		'47' => '沖縄県'
	);

	public static $prefsGeoIP = array(
	        "01" => "愛知県",
	        "02" => "秋田県",
	        "03" => "青森県",
	        "04" => "千葉県",
	        "05" => "愛媛県",
	        "06" => "福井県",
	        "07" => "福岡県",
	        "08" => "福島県",
	        "09" => "岐阜県",
	        "10" => "群馬県",
	        "11" => "広島県",
	        "12" => "北海道",
	        "13" => "兵庫県",
	        "14" => "茨城県",
	        "15" => "石川県",
	        "16" => "岩手県",
	        "17" => "香川県",
	        "18" => "鹿児島県",
	        "19" => "神奈川県",
	        "20" => "高知県",
	        "21" => "熊本県",
	        "22" => "京都府",
	        "23" => "三重県",
	        "24" => "宮城県",
	        "25" => "宮崎県",
	        "26" => "長野県",
	        "27" => "長崎県",
	        "28" => "奈良県",
	        "29" => "新潟県",
	        "30" => "大分県",
	        "31" => "岡山県",
	        "32" => "大阪府",
	        "33" => "佐賀県",
	        "34" => "埼玉県",
	        "35" => "滋賀県",
	        "36" => "島根県",
	        "37" => "静岡県",
	        "38" => "栃木県",
	        "39" => "徳島県",
	        "40" => "東京都",
	        "41" => "鳥取県",
	        "42" => "富山県",
	        "43" => "和歌山県",
	        "44" => "山形県",
	        "45" => "山口県",
	        "46" => "山梨県",
	        "47" => "沖縄県"
	);

	public static $prefsAlpha = array(
		'hokkaido',
		'aomori',
		'iwate',
		'miyagi',
		'akita',
		'yamagata',
		'fukushima',
		'ibaraki',
		'tochigi',
		'gunma',
		'saitama',
		'chiba',
		'tokyo',
		'kanagawa',
		'niigata',
		'toyama',
		'ishikawa',
		'fukui',
		'yamanashi',
		'nagano',
		'gifu',
		'shizuoka',
		'aichi',
		'mie',
		'shiga',
		'kyoto',
		'osaka',
		'hyogo',
		'nara',
		'wakayama',
		'tottori',
		'shimane',
		'okayama',
		'hiroshima',
		'yamaguchi',
		'tokushima',
		'kagawa',
		'ehime',
		'kochi',
		'fukuoka',
		'saga',
		'nagasaki',
		'kumamoto',
		'oita',
		'miyazaki',
		'kagoshima',
		'okinawa'
	);

	public static $cities = array(
		'sapporo',
		'hakodate',
		'otaru',
		'asahikawa',
		'muroran',
		'kushiro',
		'obihiro',
		'kitami',
		'yubari',
		'iwamizawa',
		'abashiri',
		'rumoi',
		'tomakomai',
		'wakkanai',
		'bibai',
		'ashibetsu',
		'ebetsu',
		'akabira',
		'mombetsu',
		'shibetsu',
		'nayoro',
		'mikasa',
		'nemuro',
		'chitose',
		'takikawa',
		'sunagawa',
		'utashinai',
		'fukagawa',
		'furano',
		'noboribetsu',
		'eniwa',
		'date',
		'kitahiroshima',
		'ishikari',
		'hokuto',
		'matsumae',
		'kamiiso',
		'kameda',
		'kayabe',
		'futami',
		'yamakoshi',
		'hiyama',
		'nishi',
		'okushiri',
		'setana',
		'kudo',
		'shimamaki',
		'suttsu',
		'isoya',
		'abuta',
		'iwanai',
		'furu',
		'shakotan',
		'furubira',
		'yoichi',
		'sorachi',
		'kabato',
		'uryu',
		'kamikawa',
		'yufutsu',
		'nakagawa',
		'mashike',
		'tomamae',
		'teshio',
		'soya',
		'esashi',
		'rebun',
		'rishiri',
		'shari',
		'tokoro',
		'usu',
		'shiraoi',
		'saru',
		'niikappu',
		'urakawa',
		'samani',
		'horoizumi',
		'hidaka',
		'kato',
		'kasai',
		'hiro',
		'ashoro',
		'tokachi',
		'akkeshi',
		'kawakami',
		'akan',
		'shiranuka',
		'notsuke',
		'menashi',
		'aomori',
		'hirosaki',
		'hachinohe',
		'kuroishi',
		'goshogawara',
		'towada',
		'misawa',
		'mutsu',
		'tsugaru',
		'hirakawa',
		'higashitsugaru',
		'nishitsugaru',
		'nakatsugaru',
		'minamitsugaru',
		'kitatsugaru',
		'kamikita',
		'shimokita',
		'sannohe',
		'morioka',
		'miyako',
		'ofunato',
		'hanamaki',
		'kitakami',
		'kuji',
		'tono',
		'ichinoseki',
		'rikuzentakata',
		'kamaishi',
		'ninohe',
		'hachimantai',
		'oshu',
		'takizawa',
		'iwate',
		'shiwa',
		'waga',
		'isawa',
		'nishiiwai',
		'kesen',
		'kamihei',
		'shimohei',
		'kunohe',
		'sendai',
		'ishinomaki',
		'shiogama',
		'kesennuma',
		'shiroishi',
		'natori',
		'kakuda',
		'tagajo',
		'iwanuma',
		'tome',
		'kurihara',
		'higashimatsushima',
		'osaki',
		'katta',
		'shibata',
		'igu',
		'watari',
		'miyagi',
		'kurokawa',
		'kami',
		'toda',
		'oshika',
		'motoyoshi',
		'akita',
		'noshiro',
		'yokote',
		'odate',
		'oga',
		'yuzawa',
		'kazuno',
		'yurihonjo',
		'katagami',
		'daisen',
		'kitaakita',
		'nikaho',
		'semboku',
		'yamamoto',
		'minamiakita',
		'ogachi',
		'yamagata',
		'yonezawa',
		'tsuruoka',
		'sakata',
		'shinjo',
		'sagae',
		'kaminoyama',
		'murayama',
		'nagai',
		'tendo',
		'higashine',
		'obanazawa',
		'nanyo',
		'higashimurayama',
		'nishimurayama',
		'kitamurayama',
		'mogami',
		'higashiokitama',
		'nishiokitama',
		'higashitagawa',
		'akumi',
		'fukushima',
		'aizuwakamatsu',
		'koriyama',
		'iwaki',
		'shirakawa',
		'sukagawa',
		'kitakata',
		'soma',
		'nihommatsu',
		'tamura',
		'minamisoma',
		'motomiya',
		'adachi',
		'iwase',
		'minamiaizu',
		'yama',
		'kawanuma',
		'onuma',
		'nishishirakawa',
		'higashishirakawa',
		'ishikawa',
		'futaba',
		'mito',
		'hitachi',
		'tsuchiura',
		'koga',
		'ishioka',
		'yuki',
		'ryugasaki',
		'shimotsuma',
		'joso',
		'hitachiota',
		'takahagi',
		'kitaibaraki',
		'kasama',
		'toride',
		'ushiku',
		'tsukuba',
		'hitachinaka',
		'kashima',
		'itako',
		'moriya',
		'hitachiomiya',
		'naka',
		'chikusei',
		'bando',
		'inashiki',
		'kasumigaura',
		'sakuragawa',
		'kamisu',
		'namegata',
		'hokota',
		'tsukubamirai',
		'omitama',
		'higashiibaraki',
		'sashima',
		'kitasoma',
		'utsunomiya',
		'ashikaga',
		'tochigi',
		'sano',
		'kanuma',
		'nikko',
		'oyama',
		'moka',
		'otawara',
		'yaita',
		'nasushiobara',
		'sakura',
		'nasukarasuyama',
		'shimotsuke',
		'kawachi',
		'haga',
		'shimotsuga',
		'shioya',
		'nasu',
		'maebashi',
		'takasaki',
		'kiryu',
		'isesaki',
		'ota',
		'numata',
		'tatebayashi',
		'shibukawa',
		'fujioka',
		'tomioka',
		'annaka',
		'midori',
		'kitagumma',
		'tano',
		'kanra',
		'agatsuma',
		'tone',
		'sawa',
		'ora',
		'saitama',
		'kawagoe',
		'kumagaya',
		'kawaguchi',
		'gyoda',
		'chichibu',
		'tokorozawa',
		'hanno',
		'kazo',
		'honjo',
		'higashimatsuyama',
		'kasukabe',
		'sayama',
		'hanyu',
		'konosu',
		'fukaya',
		'ageo',
		'soka',
		'koshigaya',
		'warabi',
		'iruma',
		'asaka',
		'shiki',
		'wako',
		'niiza',
		'okegawa',
		'kuki',
		'kitamoto',
		'yashio',
		'fujimi',
		'misato',
		'hasuda',
		'sakado',
		'satte',
		'tsurugashima',
		'yoshikawa',
		'fujimino',
		'shiraoka',
		'kitaadachi',
		'hiki',
		'kodama',
		'osato',
		'minamisaitama',
		'kitakatsushika',
		'chiba',
		'choshi',
		'ichikawa',
		'funabashi',
		'tateyama',
		'kisarazu',
		'matsudo',
		'noda',
		'mobara',
		'narita',
		'togane',
		'asahi',
		'narashino',
		'kashiwa',
		'katsura',
		'ichihara',
		'nagareyama',
		'yachiyo',
		'abiko',
		'kamogawa',
		'kamagaya',
		'kimitsu',
		'futtsu',
		'urayasu',
		'yotsukaido',
		'sodegaura',
		'yachimata',
		'inzai',
		'shiroi',
		'tomisato',
		'minamiboso',
		'sosa',
		'katori',
		'sammu',
		'isumi',
		'oamishirasato',
		'imba',
		'sambu',
		'chosei',
		'awa',
		'chiyoda',
		'chuo',
		'minato',
		'shinjuku',
		'bunkyo',
		'taito',
		'sumida',
		'koto',
		'shinagawa',
		'meguro',
		'setagaya',
		'shibuya',
		'nakano',
		'suginami',
		'toshima',
		'kita',
		'arakawa',
		'itabashi',
		'nerima',
		'katsushika',
		'edogawa',
		'hachioji',
		'tachikawa',
		'musashino',
		'mitaka',
		'ome',
		'fuchu',
		'akishima',
		'chofu',
		'machida',
		'koganei',
		'kodaira',
		'hino',
		'kokubunji',
		'kunitachi',
		'fussa',
		'komae',
		'higashiyamato',
		'kiyose',
		'higashikurume',
		'musashimurayama',
		'tama',
		'inagi',
		'hamura',
		'akiruno',
		'nishitokyo',
		'nishitama',
		'oshima',
		'niijima',
		'kozushima',
		'miyakejima',
		'mikurajima',
		'hachijojima',
		'aogashima',
		'ogasawara',
		'yokohama',
		'kawasaki',
		'sagamihara',
		'yokosuka',
		'hiratsuka',
		'kamakura',
		'fujisawa',
		'odawara',
		'chigasaki',
		'zushi',
		'miura',
		'hadano',
		'atsugi',
		'yamato',
		'isehara',
		'ebina',
		'zama',
		'minamiashigara',
		'ayase',
		'koza',
		'ashigarakami',
		'ashigarashimo',
		'aiko',
		'niigata',
		'nagaoka',
		'sanjo',
		'kashiwazaki',
		'ojiya',
		'kamo',
		'tokamachi',
		'mitsuke',
		'murakami',
		'tsubame',
		'itoigawa',
		'myoko',
		'gosen',
		'joetsu',
		'agano',
		'sado',
		'uonuma',
		'minamiuonuma',
		'tainai',
		'kitakambara',
		'nishikambara',
		'minamikambara',
		'higashikambara',
		'santo',
		'nakauonuma',
		'kariwa',
		'iwafune',
		'toyama',
		'takaoka',
		'uozu',
		'himi',
		'namerikawa',
		'kurobe',
		'tonami',
		'oyabe',
		'nanto',
		'imizu',
		'nakaniikawa',
		'shimoniikawa',
		'kanazawa',
		'nanao',
		'komatsu',
		'wajima',
		'suzu',
		'kaga',
		'hakui',
		'kahoku',
		'hakusan',
		'nomi',
		'nonoichi',
		'hosu',
		'fukui',
		'tsuruga',
		'obama',
		'ono',
		'katsuyama',
		'sabae',
		'awara',
		'echizen',
		'sakai',
		'yoshida',
		'imadate',
		'nanjo',
		'nyu',
		'mikata',
		'oi',
		'mikatakaminaka',
		'kofu',
		'fujiyoshida',
		'tsuru',
		'yamanashi',
		'otsuki',
		'nirasaki',
		'minamiarupusu',
		'kai',
		'fuefuki',
		'uenohara',
		'koshu',
		'nishiyatsushiro',
		'minamikoma',
		'nakakoma',
		'minamitsuru',
		'kitatsuru',
		'nagano',
		'matsumoto',
		'ueda',
		'okaya',
		'iida',
		'suwa',
		'suzaka',
		'komoro',
		'ina',
		'komagane',
		'omachi',
		'iiyama',
		'chino',
		'shiojiri',
		'saku',
		'chikuma',
		'tomi',
		'azumino',
		'minamisaku',
		'kitasaku',
		'chiisagata',
		'kamiina',
		'shimoina',
		'kiso',
		'higashichikuma',
		'kitaazumi',
		'hanishina',
		'kamitakai',
		'shimotakai',
		'kamiminochi',
		'shimominochi',
		'gifu',
		'ogaki',
		'takayama',
		'tajimi',
		'seki',
		'nakatsugawa',
		'mino',
		'mizunami',
		'hashima',
		'ena',
		'minokamo',
		'toki',
		'kakamigahara',
		'kani',
		'mizuho',
		'hida',
		'motosu',
		'gujo',
		'gero',
		'kaizu',
		'yoro',
		'fuwa',
		'ampachi',
		'ibi',
		'shizuoka',
		'hamamatsu',
		'numazu',
		'atami',
		'mishima',
		'fujinomiya',
		'ito',
		'shimada',
		'fuji',
		'iwata',
		'yaizu',
		'kakegawa',
		'fujieda',
		'gotemba',
		'fukuroi',
		'shimoda',
		'susono',
		'kosai',
		'izu',
		'omaezaki',
		'kikugawa',
		'izunokuni',
		'makinohara',
		'tagata',
		'sunto',
		'haibara',
		'shuchi',
		'nagoya',
		'toyohashi',
		'okazaki',
		'ichinomiya',
		'seto',
		'handa',
		'kasugai',
		'toyokawa',
		'tsushima',
		'hekinan',
		'kariya',
		'toyota',
		'anjo',
		'nishio',
		'gamagori',
		'inuyama',
		'tokoname',
		'konan',
		'komaki',
		'inazawa',
		'shinshiro',
		'tokai',
		'obu',
		'chita',
		'chiryu',
		'owariasahi',
		'takahama',
		'iwakura',
		'toyoake',
		'nisshin',
		'tahara',
		'aisai',
		'kiyosu',
		'kitanagoya',
		'yatomi',
		'miyoshi',
		'ama',
		'nagakute',
		'aichi',
		'nishikasugai',
		'niwa',
		'nukata',
		'kitashitara',
		'tsu',
		'yokkaichi',
		'ise',
		'matsusaka',
		'kuwana',
		'suzuka',
		'nabari',
		'owase',
		'kameyama',
		'toba',
		'kumano',
		'inabe',
		'shima',
		'iga',
		'mie',
		'taki',
		'watarai',
		'kitamuro',
		'minamimuro',
		'otsu',
		'hikone',
		'nagahama',
		'omihachiman',
		'kusatsu',
		'moriyama',
		'ritto',
		'koka',
		'yasu',
		'takashima',
		'higashiomi',
		'maibara',
		'gamo',
		'echi',
		'inukami',
		'kyoto',
		'fukuchiyama',
		'maizuru',
		'ayabe',
		'uji',
		'miyazu',
		'kameoka',
		'joyo',
		'muko',
		'nagaokakyo',
		'yawata',
		'kyotanabe',
		'kyotango',
		'nantan',
		'kizugawa',
		'otokuni',
		'kuse',
		'tsuzuki',
		'soraku',
		'funai',
		'yosa',
		'osaka',
		'kishiwada',
		'toyonaka',
		'ikeda',
		'suita',
		'izumiotsu',
		'takatsuki',
		'kaizuka',
		'moriguchi',
		'hirakata',
		'ibaraki',
		'yao',
		'izumisano',
		'tondabayashi',
		'neyagawa',
		'kawachinagano',
		'matsubara',
		'daito',
		'izumi',
		'kashiwara',
		'habikino',
		'kadoma',
		'settsu',
		'takaishi',
		'fujiidera',
		'higashiosaka',
		'sennan',
		'shijonawate',
		'katano',
		'osakasayama',
		'hannan',
		'toyono',
		'minamikawachi',
		'kobe',
		'himeji',
		'amagasaki',
		'akashi',
		'nishinomiya',
		'sumoto',
		'ashiya',
		'itami',
		'aioi',
		'toyoka',
		'kakogawa',
		'ako',
		'nishiwaki',
		'takarazuka',
		'miki',
		'takasago',
		'kawanishi',
		'sanda',
		'sasayama',
		'yabu',
		'tamba',
		'minamiawaji',
		'asago',
		'awaji',
		'shiso',
		'tatsuno',
		'kawabe',
		'taka',
		'kako',
		'kanzaki',
		'ibo',
		'sayo',
		'nara',
		'yamatotakada',
		'yamatokoriyama',
		'tenri',
		'kashihara',
		'sakurai',
		'gojo',
		'gose',
		'ikoma',
		'kashiba',
		'katsuragi',
		'uda',
		'yamabe',
		'takaichi',
		'kitakatsuragi',
		'yoshino',
		'wakayama',
		'kainan',
		'hashimoto',
		'arida',
		'gobo',
		'tanabe',
		'shingu',
		'kinokawa',
		'iwade',
		'kaiso',
		'nishimuro',
		'higashimuro',
		'tottori',
		'yonago',
		'kurayoshi',
		'sakaiminato',
		'iwami',
		'yazu',
		'tohaku',
		'saihaku',
		'matsue',
		'hamada',
		'izumo',
		'masuda',
		'oda',
		'yasugi',
		'gotsu',
		'unnan',
		'nita',
		'iishi',
		'ochi',
		'kanoashi',
		'oki',
		'okayama',
		'kurashiki',
		'tsuyama',
		'tamano',
		'kasaoka',
		'ibara',
		'soja',
		'takahashi',
		'niimi',
		'bizen',
		'setochi',
		'akaiwa',
		'maniwa',
		'mimasaka',
		'asakuchi',
		'wake',
		'tsukubo',
		'tomata',
		'katsuta',
		'aida',
		'kume',
		'hiroshima',
		'kure',
		'takehara',
		'mihara',
		'onomichi',
		'fukuyama',
		'shobara',
		'otake',
		'higashihiroshima',
		'hatsukaichi',
		'akitakata',
		'etajima',
		'aki',
		'sera',
		'jinseki',
		'shimonoseki',
		'ube',
		'yamaguchi',
		'hagi',
		'hofu',
		'kudamatsu',
		'iwakuni',
		'hikari',
		'nagato',
		'yanai',
		'mine',
		'shunan',
		'sanyoonoda',
		'kuga',
		'kumage',
		'abu',
		'tokushima',
		'naruto',
		'komatsushima',
		'anan',
		'yoshinogawa',
		'mima',
		'myodo',
		'myozai',
		'kaifu',
		'itano',
		'takamatsu',
		'marugame',
		'sakaide',
		'zentsuji',
		'kanonji',
		'sanuki',
		'higashikagawa',
		'mitoyo',
		'shozu',
		'kagawa',
		'ayauta',
		'nakatado',
		'matsuyama',
		'imabari',
		'uwajima',
		'yawatahama',
		'niihama',
		'saijo',
		'ozu',
		'iyo',
		'shikokuchuo',
		'seiyo',
		'toon',
		'kamiukena',
		'nishiuwa',
		'kitauwa',
		'minamiuwa',
		'kochi',
		'muroto',
		'nankoku',
		'tosa',
		'susaki',
		'sukumo',
		'tosashimizu',
		'shimanto',
		'agawa',
		'hata',
		'kitakyushu',
		'fukuoka',
		'omuta',
		'kurume',
		'nogata',
		'iizuka',
		'tagawa',
		'yanagawa',
		'yame',
		'chikugo',
		'okawa',
		'yukuhashi',
		'buzen',
		'nakama',
		'ogori',
		'chikushino',
		'kasuga',
		'onojo',
		'munakata',
		'dazaifu',
		'fukutsu',
		'ukiha',
		'miyawaka',
		'kama',
		'asakura',
		'miyama',
		'itoshima',
		'chikushi',
		'kasuya',
		'onga',
		'kurate',
		'kaho',
		'mii',
		'mizuma',
		'chikujo',
		'saga',
		'karatsu',
		'tosu',
		'taku',
		'imari',
		'takeo',
		'ogi',
		'ureshino',
		'miyaki',
		'higashimatsura',
		'nishimatsura',
		'kishima',
		'fujitsu',
		'nagasaki',
		'sasebo',
		'shimabara',
		'isahaya',
		'omura',
		'hirado',
		'matsura',
		'iki',
		'goto',
		'saikai',
		'unzen',
		'minamishimabara',
		'nishisonogi',
		'higashisonogi',
		'kitamatsura',
		'minamimatsura',
		'kumamoto',
		'yatsushiro',
		'hitoyoshi',
		'arao',
		'minamata',
		'tamana',
		'yamaga',
		'kikuchi',
		'uto',
		'kamiamakusa',
		'uki',
		'aso',
		'amakusa',
		'koshi',
		'shimomashiki',
		'kamimashiki',
		'ashikita',
		'kuma',
		'oita',
		'beppu',
		'nakatsu',
		'hita',
		'saiki',
		'usuki',
		'tsukumi',
		'taketa',
		'bungotakada',
		'kitsuki',
		'usa',
		'bungoono',
		'yufu',
		'kunisaki',
		'higashikunisaki',
		'hayami',
		'kusu',
		'miyazaki',
		'miyakonojo',
		'nobeoka',
		'nichinan',
		'kobayashi',
		'hyuga',
		'kushima',
		'saito',
		'ebino',
		'kitamorokata',
		'nishimorokata',
		'higashimorokata',
		'koyu',
		'higashiusuki',
		'nishiusuki',
		'kagoshima',
		'kanoya',
		'makurazaki',
		'akune',
		'ibusuki',
		'nishinomote',
		'tarumizu',
		'satsumasendai',
		'hioki',
		'so',
		'kirishima',
		'ichikikushikino',
		'minamisatsuma',
		'shibushi',
		'amami',
		'minamikyushu',
		'isa',
		'aira',
		'satsuma',
		'kimotsuki',
		'naha',
		'ginowan',
		'ishigaki',
		'urasoe',
		'nago',
		'itoman',
		'okinawa',
		'tomigusuku',
		'uruma',
		'miyakojima',
		'kunigami',
		'nakagami',
		'shimajiri',
		'yaeyama'
	);

	public static $prefKeywords = array(
		'asahikawa'		=> '01',
		'ashk'			=> '01',
		'chitose'		=> '01',
		'ctse'			=> '01',
		'hakodate'		=> '01',
		'hkd'			=> '01',
		'hkdt'			=> '01',
		'hkid'			=> '01',
		'hokkaido'		=> '01',
		'hokkaidoa'		=> '01',
		'ksro'			=> '01',
		'ktmi'			=> '01',
		'kushiro'		=> '01',
		'kusr'			=> '01',
		'mrrn'			=> '01',
		'muroran'		=> '01',
		'obhr'			=> '01',
		'obihiro'		=> '01',
		'otaru'			=> '01',
		'otru'			=> '01',
		'sapporo'		=> '01',
		'sapporokita'		=> '01',
		'sapporonishi'		=> '01',
		'sappr'			=> '01',
		'sppr'			=> '01',
		'spro'			=> '01',
		'takikawa'		=> '01',
		'tkgw'			=> '01',
		'tmkm'			=> '01',
		'tomakomai'		=> '01',
		'ttse'			=> '01',
		'aom'			=> '02',
		'aomori'		=> '02',
		'aomoria'		=> '02',
		'aomr'			=> '02',
		'hachinohe'		=> '02',
		'hcnh'			=> '02',
		'hirosaki'		=> '02',
		'hrsk'			=> '02',
		'ichinoseki'		=> '03',
		'iwa'			=> '03',
		'iwade'			=> '03',
		'iwat'			=> '03',
		'iwate'			=> '03',
		'iwte'			=> '03',
		'morioka'		=> '03',
		'mrok'			=> '03',
		'ismk'			=> '04',
		'isnm'			=> '04',
		'miyagi'		=> '04',
		'miyagia'		=> '04',
		'miyg'			=> '04',
		'myg'			=> '04',
		'mygi'			=> '04',
		'ogwr'			=> '04',
		'sendai'		=> '04',
		'sndi'			=> '04',
		'aki'			=> '05',
		'akit'			=> '05',
		'akita'			=> '05',
		'akitaa'		=> '05',
		'akt'			=> '05',
		'akta'			=> '05',
		'sakata'		=> '06',
		'skta'			=> '06',
		'trok'			=> '06',
		'yamagata'		=> '06',
		'yamagataa'		=> '06',
		'ygt'			=> '06',
		'ymg'			=> '06',
		'ymgt'			=> '06',
		'ynzw'			=> '06',
		'yonezawa'		=> '06',
		'aizu'			=> '07',
		'fks'			=> '07',
		'fksm'			=> '07',
		'fukushima'		=> '07',
		'fukushimaa'		=> '07',
		'fukusima'		=> '07',
		'iwak'			=> '07',
		'iwaki'			=> '07',
		'iwki'			=> '07',
		'kooriyama'		=> '07',
		'koriyama'		=> '07',
		'krym'			=> '07',
		'shirakawa'		=> '07',
		'akatsuka'		=> '08',
		'furukawa'		=> '08',
		'hitachi'		=> '08',
		'hitachioota'		=> '08',
		'hitachiota'		=> '08',
		'htch'			=> '08',
		'iba'			=> '08',
		'ibaragi'		=> '08',
		'ibaraki'		=> '08',
		'ibr'			=> '08',
		'ishioka'		=> '08',
		'isok'			=> '08',
		'itak'			=> '08',
		'itako'			=> '08',
		'koga'			=> '08',
		'ksma'			=> '08',
		'mito'			=> '08',
		'mtki'			=> '08',
		'rccx'			=> '08',
		'rygs'			=> '08',
		'ryugasaki'		=> '08',
		'shimodate'		=> '08',
		'smdt'			=> '08',
		'tcur'			=> '08',
		'tkba'			=> '08',
		'tsuchiura'		=> '08',
		'tsukuba'		=> '08',
		'ashikaga'		=> '09',
		'askg'			=> '09',
		'kyma'			=> '09',
		'ohtawara'		=> '09',
		'otawara'		=> '09',
		'otwr'			=> '09',
		'oyam'			=> '09',
		'oyama'			=> '09',
		'oyma'			=> '09',
		'sano'			=> '09',
		'tcg'			=> '09',
		'tcgi'			=> '09',
		'tocg'			=> '09',
		'tochigi'		=> '09',
		'totigi'		=> '09',
		'utnm'			=> '09',
		'utsunomiya'		=> '09',
		'utunomiya'		=> '09',
		'gnm'			=> '10',
		'gnma'			=> '10',
		'gunm'			=> '10',
		'gunma'			=> '10',
		'isesaki'		=> '10',
		'iszk'			=> '10',
		'kiryu'			=> '10',
		'kryu'			=> '10',
		'maebashi'		=> '10',
		'maebs'			=> '10',
		'mebs'			=> '10',
		'ota'			=> '10',
		'sbkw'			=> '10',
		'shibukawa'		=> '10',
		'takasaki'		=> '10',
		'tatebayashi'		=> '10',
		'tksk'			=> '10',
		'ttby'			=> '10',
		'asaka'			=> '11',
		'hann'			=> '11',
		'hanno'			=> '11',
		'hgsm'			=> '11',
		'higashimatsuyama'	=> '11',
		'higashi-matsuyama'	=> '11',
		'hmty'			=> '11',
		'hnjo'			=> '11',
		'hnnu'			=> '11',
		'honjo'			=> '11',
		'kawagoe'		=> '11',
		'kawaguchi'		=> '11',
		'kgci'			=> '11',
		'kmgy'			=> '11',
		'koshigaya'		=> '11',
		'ksgy'			=> '11',
		'kuki'			=> '11',
		'kumagaya'		=> '11',
		'kwgc'			=> '11',
		'kwge'			=> '11',
		'kwgw'			=> '11',
		'omiya'			=> '11',
		'saitama'		=> '11',
		'sakado'		=> '11',
		'shiki'			=> '11',
		'sitm'			=> '11',
		'soka'			=> '11',
		'souka'			=> '11',
		'stama'			=> '11',
		'stm'			=> '11',
		'tkrz'			=> '11',
		'tokorozawa'		=> '11',
		'uraw'			=> '11',
		'urawa'			=> '11',
		'urw'			=> '11',
		'urwa'			=> '11',
		'yono'			=> '11',
		'chb'			=> '12',
		'chba'			=> '12',
		'chib'			=> '12',
		'chiba'			=> '12',
		'choushi'		=> '12',
		'fnbs'			=> '12',
		'funabashi'		=> '12',
		'funabasi'		=> '12',
		'ichihara'		=> '12',
		'ichikawa'		=> '12',
		'ichr'			=> '12',
		'ickw'			=> '12',
		'kashiwa'		=> '12',
		'kasiw'			=> '12',
		'kasw'			=> '12',
		'kisarazu'		=> '12',
		'kmts'			=> '12',
		'ksrz'			=> '12',
		'ksrzu'			=> '12',
		'kswa'			=> '12',
		'makuhari'		=> '12',
		'matsudo'		=> '12',
		'mbra'			=> '12',
		'mobara'		=> '12',
		'mobr'			=> '12',
		'mtdo'			=> '12',
		'narashino'		=> '12',
		'narita'		=> '12',
		'nrit'			=> '12',
		'nrta'			=> '12',
		'o-ichikawa'		=> '12',
		'sawara'		=> '12',
		'shra'			=> '12',
		'togane'		=> '12',
		'togn'			=> '12',
		'tugn'			=> '12',
		'urayasu'		=> '12',
		'yuib'			=> '12',
		'chfu'			=> '13',
		'chofu'			=> '13',
		'edgwa'			=> '13',
		'fchu'			=> '13',
		'fuchu'			=> '13',
		'hachiohji'		=> '13',
		'hachioji'		=> '13',
		'hachiouji'		=> '13',
		'haci'			=> '13',
		'hcou'			=> '13',
		'hino'			=> '13',
		'ingi'			=> '13',
		'itabs'			=> '13',
		'kichijoji'		=> '13',
		'kkbnj'			=> '13',
		'kodaira'		=> '13',
		'koganei'		=> '13',
		'kokubunji'		=> '13',
		'k-tokyo'		=> '13',
		'ktsk'			=> '13',
		'kunitachi'		=> '13',
		'machida'		=> '13',
		'mcda'			=> '13',
		'mitaka'		=> '13',
		'mtak'			=> '13',
		'musashino'		=> '13',
		'musashino-mitaka'	=> '13',
		'nihonbashi'		=> '13',
		'nishitokyo'		=> '13',
		'nkno'			=> '13',
		'nrima'			=> '13',
		'ntky'			=> '13',
		'ntkyo'			=> '13',
		'ohme'			=> '13',
		'ohta'			=> '13',
		'ome'			=> '13',
		'o-tokyo'		=> '13',
		'oume'			=> '13',
		'shinjuku'		=> '13',
		's-tokyo'		=> '13',
		'tachikawa'		=> '13',
		'tama'			=> '13',
		'tckw'			=> '13',
		'tk'			=> '13',
		'tkbn'			=> '13',
		'tky'			=> '13',
		'tkyo'			=> '13',
		'toky'			=> '13',
		'tokyo'			=> '13',
		't-tokyo'		=> '13',
		'atgi'			=> '14',
		'atsugi'		=> '14',
		'chgsk'			=> '14',
		'ebina'			=> '14',
		'fjsw'			=> '14',
		'fjswa'			=> '14',
		'fujisawa'		=> '14',
		'hiratsuka'		=> '14',
		'hrtk'			=> '14',
		'isehara'		=> '14',
		'kanagawa'		=> '14',
		'kanagawashinmachi'	=> '14',
		'kawasaki'		=> '14',
		'kawasakibekkan'	=> '14',
		'k-fujisawa'		=> '14',
		'kng'			=> '14',
		'kngw'			=> '14',
		'kwsk'			=> '14',
		'm-yokohama'		=> '14',
		'n-yokohama'		=> '14',
		'odawara'		=> '14',
		'odwr'			=> '14',
		'sagam'			=> '14',
		'sagami'		=> '14',
		'sagamihara'		=> '14',
		'sgmi'			=> '14',
		'shiboguchi'		=> '14',
		's-kawasaki'		=> '14',
		'yamat'			=> '14',
		'yamato'		=> '14',
		'ykh'			=> '14',
		'ykhm'			=> '14',
		'yksk'			=> '14',
		'yokohama'		=> '14',
		'yokohamako'		=> '14',
		'yokosuka'		=> '14',
		'yoksk'			=> '14',
		'joetsu'		=> '15',
		'jyouetsu'		=> '15',
		'kashiwazaki'		=> '15',
		'nagaoka'		=> '15',
		'ngok'			=> '15',
		'nig'			=> '15',
		'nigata'		=> '15',
		'nigt'			=> '15',
		'niigata'		=> '15',
		'niigataa'		=> '15',
		'sanjyo'		=> '15',
		'takaoka'		=> '16',
		'tkok'			=> '16',
		'toyama'		=> '16',
		'toyamaa'		=> '16',
		'toym'			=> '16',
		'tym'			=> '16',
		'tyma'			=> '16',
		'ishikawa'		=> '17',
		'isk'			=> '17',
		'iskw'			=> '17',
		'kanazawa'		=> '17',
		'kmts'			=> '17',
		'knzw'			=> '17',
		'komatsu'		=> '17',
		'nnao'			=> '17',
		'fki'			=> '18',
		'fkui'			=> '18',
		'fuki'			=> '18',
		'fukui'			=> '18',
		'fukuia'		=> '18',
		'srga'			=> '18',
		'fjys'			=> '19',
		'kofu'			=> '19',
		'koufu'			=> '19',
		'kufu'			=> '19',
		'yamanashi'		=> '19',
		'ymn'			=> '19',
		'ymns'			=> '19',
		'iida'			=> '20',
		'ina-'			=> '20',
		'matsumoto'		=> '20',
		'matumoto'		=> '20',
		'mtmt'			=> '20',
		'nagano'		=> '20',
		'naganoa'		=> '20',
		'ngn'			=> '20',
		'ngno'			=> '20',
		'suwa'			=> '20',
		'ueda'			=> '20',
		'gif'			=> '21',
		'gifu'			=> '21',
		'kani'			=> '21',
		'minokamo'		=> '21',
		'mnkm'			=> '21',
		'ogak'			=> '21',
		'ogaki'			=> '21',
		'ogki'			=> '21',
		'ohgaki'		=> '21',
		'tajimi'		=> '21',
		'tajm'			=> '21',
		'tjmi'			=> '21',
		'fjnm'			=> '22',
		'fuji'			=> '22',
		'fujiyoshida'		=> '22',
		'hamamatsu'		=> '22',
		'hmmt'			=> '22',
		'ito'			=> '22',
		'itox'			=> '22',
		'iwata'			=> '22',
		'iwta'			=> '22',
		'kkeg'			=> '22',
		'ma-shizuoka'		=> '22',
		'mi-shizuoka'		=> '22',
		'nmzu'			=> '22',
		'numazu'		=> '22',
		'numz'			=> '22',
		'shimizu'		=> '22',
		'shizuoka'		=> '22',
		'sizuoka'		=> '22',
		'smiz'			=> '22',
		'smzu'			=> '22',
		'szk'			=> '22',
		'szo'			=> '22',
		'szok'			=> '22',
		'toyizu'		=> '22',
		'aic'			=> '23',
		'aich'			=> '23',
		'aichi'			=> '23',
		'aichieast'		=> '23',
		'aici'			=> '23',
		'a-nagoya'		=> '23',
		'd-nagoya'		=> '23',
		'handa'			=> '23',
		'hnda'			=> '23',
		'ichinomiya'		=> '23',
		'icnm'			=> '23',
		'kariya'		=> '23',
		'kary'			=> '23',
		'kasugai'		=> '23',
		'krya'			=> '23',
		'ksgi'			=> '23',
		'nagoya'		=> '23',
		'ngya'			=> '23',
		'okazaki'		=> '23',
		'okzk'			=> '23',
		'seto'			=> '23',
		'tkct'			=> '23',
		'tokai'			=> '23',
		'toki'			=> '23',
		'toyohashi'		=> '23',
		'toyota'		=> '23',
		'toyt'			=> '23',
		'tsma'			=> '23',
		'tsushima'		=> '23',
		'tyhs'			=> '23',
		'tyta'			=> '23',
		'ise-'			=> '24',
		'isex'			=> '24',
		'kuwana'		=> '24',
		'kwna'			=> '24',
		'mie'			=> '24',
		'mie-'			=> '24',
		'miex'			=> '24',
		'mtzk'			=> '24',
		'nbri'			=> '24',
		'tsu'			=> '24',
		'tsu-'			=> '24',
		'tsux'			=> '24',
		'ueno'			=> '24',
		'ykic'			=> '24',
		'yokkaichi'		=> '24',
		'hikn'			=> '25',
		'hikone'		=> '25',
		'hkne'			=> '25',
		'mnkc'			=> '25',
		'nagahama'		=> '25',
		'nghm'			=> '25',
		'ohtsu'			=> '25',
		'oots'			=> '25',
		'ootsu'			=> '25',
		'otsu'			=> '25',
		'oumi'			=> '25',
		'shg'			=> '25',
		'shga'			=> '25',
		'shiga'			=> '25',
		'sig'			=> '25',
		'siga'			=> '25',
		'fkcy'			=> '26',
		'fukuchiyama'		=> '26',
		'kmok'			=> '26',
		'kyot'			=> '26',
		'kyoto'			=> '26',
		'kyt'			=> '26',
		'kyto'			=> '26',
		'uji'			=> '26',
		'uji-'			=> '26',
		'ujix'			=> '26',
		'd-osaka'		=> '27',
		'hirakata'		=> '27',
		'hrkt'			=> '27',
		'ibrk'			=> '27',
		'ikda'			=> '27',
		'iked'			=> '27',
		'ikeda'			=> '27',
		'izmi'			=> '27',
		'izms'			=> '27',
		'izumi'			=> '27',
		'kishiwada'		=> '27',
		'kishiwada-kaizuka'	=> '27',
		'kswd'			=> '27',
		'minamiosaka'		=> '27',
		'neyagawa'		=> '27',
		'n-osaka'		=> '27',
		'nygw'			=> '27',
		'os'			=> '27',
		'osa'			=> '27',
		'osak'			=> '27',
		'osaka'			=> '27',
		'osakakita'		=> '27',
		'osk'			=> '27',
		'oska'			=> '27',
		'sakai'			=> '27',
		'skai'			=> '27',
		'takatsuki'		=> '27',
		'takatuki'		=> '27',
		'tktk'			=> '27',
		'tndb'			=> '27',
		'tond'			=> '27',
		'tondabayashi'		=> '27',
		't-osaka'		=> '27',
		'yao'			=> '27',
		'yao-'			=> '27',
		'yaox'			=> '27',
		'aksh'			=> '28',
		'aksi'			=> '28',
		'd-kobe'		=> '28',
		'himeji'		=> '28',
		'himj'			=> '28',
		'hmji'			=> '28',
		'hyg'			=> '28',
		'hygo'			=> '28',
		'hyog'			=> '28',
		'hyogo'			=> '28',
		'itami'			=> '28',
		'kakogawa'		=> '28',
		'kakokawa'		=> '28',
		'kasai'			=> '28',
		'kbe'			=> '28',
		'kkgw'			=> '28',
		'kkog'			=> '28',
		'kob'			=> '28',
		'kobe'			=> '28',
		'kube'			=> '28',
		'miki'			=> '28',
		'nishinomiya'		=> '28',
		'nishiwaki'		=> '28',
		'n-nishinomiya'		=> '28',
		'nsnm'			=> '28',
		'sand'			=> '28',
		'sanda'			=> '28',
		'snda'			=> '28',
		'sumoto'		=> '28',
		'yamasaki'		=> '28',
		'kshr'			=> '29',
		'nar'			=> '29',
		'nara'			=> '29',
		'nra'			=> '29',
		'takada'		=> '29',
		'yamatokashihara'	=> '29',
		'yamatotakada'		=> '29',
		'yamato-takada'		=> '29',
		'ymtk'			=> '29',
		'hashimoto'		=> '30',
		'tanabe'		=> '30',
		'wakayama'		=> '30',
		'wky'			=> '30',
		'wkym'			=> '30',
		'totr'			=> '31',
		'tottori'		=> '31',
		'tottoria'		=> '31',
		'ttr'			=> '31',
		'ttri'			=> '31',
		'yngo'			=> '31',
		'yonago'		=> '31',
		'yong'			=> '31',
		'izum'			=> '32',
		'izumo'			=> '32',
		'matsue'		=> '32',
		'mtse'			=> '32',
		'mtue'			=> '32',
		'shimane'		=> '32',
		'simn'			=> '32',
		'smn'			=> '32',
		'smne'			=> '32',
		'krsk'			=> '33',
		'kurashiki'		=> '33',
		'okayama'		=> '33',
		'okayamaa'		=> '33',
		'oky'			=> '33',
		'okym'			=> '33',
		'shinkurashiki'		=> '33',
		'fkym'			=> '34',
		'fukuyama'		=> '34',
		'hgsh'			=> '34',
		'hhrs'			=> '34',
		'higashi-hiroshima'	=> '34',
		'hiroshima'		=> '34',
		'hiroshimaa'		=> '34',
		'hirosima'		=> '34',
		'hrs'			=> '34',
		'hrsm'			=> '34',
		'kure'			=> '34',
		'm-hiroshima'		=> '34',
		'onomichi'		=> '34',
		'iwakuni'		=> '35',
		'iwkn'			=> '35',
		'shimonoseki'		=> '35',
		'shmki'			=> '35',
		'tkym'			=> '35',
		'tokuyama'		=> '35',
		'ube'			=> '35',
		'ube-'			=> '35',
		'ubex'			=> '35',
		'yamaguchi'		=> '35',
		'yamaguchia'		=> '35',
		'ygc'			=> '35',
		'ymgc'			=> '35',
		'tks'			=> '36',
		'tksm'			=> '36',
		'tokushima'		=> '36',
		'kagawa'		=> '37',
		'kagw'			=> '37',
		'kgw'			=> '37',
		'kgwa'			=> '37',
		'marugame'		=> '37',
		'mrgm'			=> '37',
		'sakaide'		=> '37',
		'takamatsu'		=> '37',
		'tkmt'			=> '37',
		'ehim'			=> '38',
		'ehime'			=> '38',
		'ehimea'		=> '38',
		'ehm'			=> '38',
		'ehme'			=> '38',
		'imabari'		=> '38',
		'imbr'			=> '38',
		'matsuyama'		=> '38',
		'mtym'			=> '38',
		'nihm'			=> '38',
		'niihama'		=> '38',
		'kch'			=> '39',
		'koc'			=> '39',
		'kochi'			=> '39',
		'koci'			=> '39',
		'kouchi'		=> '39',
		'kuch'			=> '39',
		'fkk'			=> '40',
		'fko'			=> '40',
		'fkok'			=> '40',
		'fkoka'			=> '40',
		'fuku'			=> '40',
		'fukuoka'		=> '40',
		'fukuokaa'		=> '40',
		'hakata'		=> '40',
		'hkata'			=> '40',
		'kitakyushu'		=> '40',
		'kita-kyushu'		=> '40',
		'kitakyusyu'		=> '40',
		'kitk'			=> '40',
		'kkysh'			=> '40',
		'krme'			=> '40',
		'ktks'			=> '40',
		'kurm'			=> '40',
		'kurume'		=> '40',
		'omut'			=> '40',
		'omuta'			=> '40',
		'oomt'			=> '40',
		'setaka'		=> '40',
		'te-fukuoka'		=> '40',
		'sag'			=> '41',
		'saga'			=> '41',
		'nagasaki'		=> '42',
		'nagasakia'		=> '42',
		'ngs'			=> '42',
		'ngsk'			=> '42',
		'sasebo'		=> '42',
		'ssbo'			=> '42',
		'kmm'			=> '43',
		'kmmt'			=> '43',
		'kumamoto'		=> '43',
		'kumamotoa'		=> '43',
		'yatsushiro'		=> '43',
		'ytsr'			=> '43',
		'beppu'			=> '44',
		'ohita'			=> '44',
		'oit'			=> '44',
		'oita'			=> '44',
		'ooit'			=> '44',
		'saiki'			=> '44',
		'usuki'			=> '44',
		'miyazaki'		=> '45',
		'miyazakia'		=> '45',
		'myz'			=> '45',
		'myzk'			=> '45',
		'nbok'			=> '45',
		'nobeoka'		=> '45',
		'kagoshima'		=> '46',
		'kgs'			=> '46',
		'kgsm'			=> '46',
		'nah'			=> '47',
		'naha'			=> '47',
		'okinawa'		=> '47',
		'okinawaa'		=> '47',
		'okn'			=> '47',
		'oknw'			=> '47',

		'a001'			=> '01',
		'a002'			=> '02',
		'a003'			=> '03',
		'a004'			=> '04',
		'a005'			=> '05',
		'a006'			=> '06',
		'a007'			=> '07',
		'a008'			=> '08',
		'a009'			=> '09',
		'a010'			=> '10',
		'a011'			=> '11',
		'a012'			=> '12',
		'a013'			=> '13',
		'a014'			=> '14',
		'a015'			=> '15',
		'a016'			=> '16',
		'a017'			=> '17',
		'a018'			=> '18',
		'a019'			=> '19',
		'a020'			=> '20',
		'a021'			=> '21',
		'a022'			=> '22',
		'a023'			=> '23',
		'a024'			=> '24',
		'a025'			=> '25',
		'a026'			=> '26',
		'a027'			=> '27',
		'a028'			=> '28',
		'a029'			=> '29',
		'a030'			=> '30',
		'a031'			=> '31',
		'a032'			=> '32',
		'a033'			=> '33',
		'a034'			=> '34',
		'a035'			=> '35',
		'a036'			=> '36',
		'a037'			=> '37',
		'a038'			=> '38',
		'a039'			=> '39',
		'a040'			=> '40',
		'a041'			=> '41',
		'a042'			=> '42',
		'a043'			=> '43',
		'a044'			=> '44',
		'a045'			=> '45',
		'a046'			=> '46',
		'a047'			=> '47',

		'SOD'			=> '01',
		'OKI'			=> '02',
		'MRN'			=> '03',
		'AOB'			=> '04',
		'NKD'			=> '05',
		'IMZ'			=> '06',
		'HNZ'			=> '07',
		'AKA'			=> '08',
		'HRD'			=> '09',
		'KKR'			=> '10',
		'SKN'			=> '11',
		'FNA'			=> '12',
		'HDO'			=> '14',
		'NGN'			=> '15',
		'TYN'			=> '16',
		'KNN'			=> '17',
		'FKN'			=> '18',
		'KFN'			=> '19',
		'SYD'			=> '20',
		'SDD'			=> '22',
		'SSJ'			=> '23',
		'YKM'			=> '24',
		'OTU'			=> '25',
		'KYN'			=> '26',
		'NWT'			=> '27',
		'KBM'			=> '28',
		'DAJ'			=> '29',
		'WKN'			=> '30',
		'TTN'			=> '31',
		'SMN'			=> '32',
		'IMM'			=> '33',
		'NIH'			=> '34',
		'YGN'			=> '35',
		'TKN'			=> '36',
		'TMN'			=> '37',
		'MYN'			=> '38',
		'KCM'			=> '39',
		'FKC'			=> '40',
		'TGS'			=> '41',
		'SCO'			=> '42',
		'OBY'			=> '43',
		'OMC'			=> '44',
		'MZN'			=> '45',
		'KMI'			=> '46',
		'YRM'			=> '47'
	);

	public static $prefWords = array(
		'hokkaido'	=> '01',
		'aomori'	=> '02',
		'iwate'		=> '03',
		'miyagi'	=> '04',
		'akita'		=> '05',
		'yamagata'	=> '06',
		'fukushima'	=> '07',
		'ibaraki'	=> '08',
		'tochigi'	=> '09',
		'gunma'		=> '10',
		'saitama'	=> '11',
		'chiba'		=> '12',
		'tokyo'		=> '13',
		'kanagawa'	=> '14',
		'niigata'	=> '15',
		'toyama'	=> '16',
		'ishikawa'	=> '17',
		'fukui'		=> '18',
		'yamanashi'	=> '19',
		'nagano'	=> '20',
		'gifu'		=> '21',
		'shizuoka'	=> '22',
		'aichi'		=> '23',
		'mie'		=> '24',
		'shiga'		=> '25',
		'kyoto'		=> '26',
		'osaka'		=> '27',
		'hyogo'		=> '28',
		'nara'		=> '29',
		'wakayama'	=> '30',
		'tottori'	=> '31',
		'shimane'	=> '32',
		'okayama'	=> '33',
		'hiroshima'	=> '34',
		'yamaguchi'	=> '35',
		'tokushima'	=> '36',
		'kagawa'	=> '37',
		'ehime'		=> '38',
		'kochi'		=> '39',
		'fukuoka'	=> '40',
		'saga'		=> '41',
		'nagasaki'	=> '42',
		'kumamoto'	=> '43',
		'oita'		=> '44',
		'miyazaki'	=> '45',
		'kagoshima'	=> '46',
		'okinawa'	=> '47'
	);
}
?>
