CREATE TABLE IF NOT EXISTS ? (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
domain VARCHAR( 255 ) NOT UNIQUE NULL COMMENT 'ドメイン',
name VARCHAR( 255 ) NOT NULL COMMENT 'ドメイン名',
created_on DATETIME COMMENT '登録日時',
updated_on DATETIME COMMENT '更新日時',
PRIMARY KEY (id) 
)
TYPE = InnoDB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 70
CHECKSUM = 0
MAX_ROWS = 100000
MIN_ROWS = 1
ROW_FORMAT = DEFAULT
COMMENT = 'ドメインマスタ'
;
