CREATE TABLE IF NOT EXISTS ? (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
version VARCHAR( 10 ) NOT NULL DEFAULT '0' COMMENT 'バージョン',
timezone VARCHAR( 50 ) NOT NULL DEFAULT 'default' COMMENT 'タイムゾーン',
apploglevel VARCHAR( 10 ) NOT NULL DEFAULT 'ALL' COMMENT 'アプリケーションログレベル',
created_on DATETIME COMMENT '登録日時',
updated_on DATETIME COMMENT '更新日時',
PRIMARY KEY (id) 
)
TYPE = InnoDB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 10
CHECKSUM = 0
MAX_ROWS = 1
MIN_ROWS = 1
ROW_FORMAT = DEFAULT
COMMENT = 'システムマスタ'
;
