CREATE TABLE IF NOT EXISTS ? (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
url TEXT NOT NULL COMMENT 'URL',
title TEXT NOT NULL COMMENT 'タイトル',
logtype CHAR( 1 )  NOT NULL COMMENT 'ログタイプ',
created_on DATETIME COMMENT '登録日時',
updated_on DATETIME COMMENT '更新日時',
PRIMARY KEY ( id ) ,  
UNIQUE idx_title (url(255)) 
)
TYPE = InnoDB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 100
CHECKSUM = 0
MAX_ROWS = 100000
MIN_ROWS = 1
ROW_FORMAT = DEFAULT
COMMENT = 'タイトルマスタ'
;
