CREATE TABLE IF NOT EXISTS ? (
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
sitename VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'サイト名',
url VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'URL',
loginid VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'ユーザー名',
pswd VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'パスワード',
dispview SMALLINT NOT NULL DEFAULT 30 COMMENT '画面明細表示件数',
oksecond SMALLINT NOT NULL DEFAULT 30 COMMENT 'OKと判断される秒数',
againsecond SMALLINT NOT NULL DEFAULT 600 COMMENT '再訪問と判断される秒数',
sortkey CHAR( 1 )  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1' COMMENT 'ソートキー',
nocrawler CHAR( 1 )  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1' COMMENT 'クローラー除外',
filter TEXT CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT 'フィルター',
cookiekey VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '自動ログイン用キー',
created_on DATETIME COMMENT '登録日時',
updated_on DATETIME COMMENT '更新日時',
PRIMARY KEY (id) 
)
TYPE = InnoDB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 40
CHECKSUM = 0
MAX_ROWS = 1
MIN_ROWS = 1
ROW_FORMAT = DEFAULT
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci
COMMENT = 'サイトマスタ'
;
